-- Meal plan images storage policy
-- Created: 2026-05-29
-- Adds a SELECT policy on storage.objects allowing authenticated users to read
-- objects stored under the meal-plans/<uid>/ prefix in the private-uploads bucket.
-- Images are generated by the service role and stored at:
--   meal-plans/<user_id>/<meal_plan_id>/<meal_id>.webp
-- This policy mirrors the existing private_uploads_select_own policy which covers
-- the uploads/<uid>/ prefix only.

drop policy if exists "private_uploads_meal_plans_select_own" on storage.objects;
create policy "private_uploads_meal_plans_select_own"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'private-uploads'
  and (storage.foldername(name))[1] = 'meal-plans'
  and (storage.foldername(name))[2] = (select auth.uid())::text
);
